### ISSUE TITLE
Trace span longer than invocation

### ISSUE THREAD

**Issue by liveFreeOrCode** [DataDog/datadog-lambda-extension#10]
I don't know if this is supposed to be this way or not, but when I have my lambdas hooked up to the v8 extension my traces look something like this.  This is with x-ray merging in place as well. The green and yellow trace spans are from xray, and everything in orange is from the datadog-lambda-extension

![image](https://user-images.githubusercontent.com/12355170/122322946-4df25000-cef4-11eb-81ab-42c5d7ba09b0.png)

1. Why are there varying span lengths for `Invoke`? (I assume this is just aws nonsense, and less of a concern than the next question)
2. Why does the first span from datadog-lambda-extension go far beyond the invocation spans?

The lambda has the following layers: 
![image](https://user-images.githubusercontent.com/12355170/122323261-d113a600-cef4-11eb-8eea-e61f3351a7d5.png)

with the following environment variables (api_key not shown):
![image](https://user-images.githubusercontent.com/12355170/122323413-07512580-cef5-11eb-8dc5-2c62c969da06.png)

**Comment by maxday** [comment]
Closing this issue for now. Feel free to re-open it if you need
