### ISSUE TITLE
Send OpenTelemetry traces to the datadog via the extension

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [DataDog/datadog-lambda-extension#100]
I would like to instrument my Lambda function using OpenTelementry. I know ADOT (AWS Distro for OpenTelementry) exists but it seems that I would have to sacrifice some features (appsec, enhanced metrics, log & trace correlation, etc) if I only used that. If I used both ADOT and the Datadog extension then I'd have to include more Lambda Layers.

I would like to activate the OTLP ingestion. I tried setting the `DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=localhost:4318` environment variable but when I check the port is not in use. Is it possible to run the OTLP ingestion in lambda?

**Comment by matthias-pichler-warrify** [comment]
https://github.com/DataDog/datadog-agent/issues/11889

**Comment by DarcyRaynerDD** [comment]
Hi Matthias. Thanks for the issue, sorry for the delay in writing this response. Like it was identified in the other thread, we have stripped OTel support from the Serverless build. Unfortunately, it's a bit more complicated than reversing the build tags, we have to rearrange some internals to correctly serve the OTel API. We are currently planning work for supporting OTel directly in the extension. We'll post an update on this ticket when we have more info.

**Comment by tianchu** [comment]
cc: @purple4reina

**Comment by purple4reina** [comment]
I'm pleased to announce that we have released v41 of the [Datadog AWS Lambda Extension with OpenTelemetry support](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v41). You can enable the feature by setting either `DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=localhost:4318` or `DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=localhost:4317 ` as described [here](https://docs.datadoghq.com/opentelemetry/otlp_ingest_in_the_agent/?tab=host). Then tell your function where to send the traces by setting `OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317`. Traces will then be discoverable in the Datadog UI.

**Comment by jamiewinder** [comment]
Is there any more to this other than setting the environment variable? I can see trace relating to the Lambda, but the traces generated by my service don't seem to be getting received (or forwarded?) by the agent.

**Comment by duncanista** [comment]
🐸  Hey everyone,

I'm going to close this ticket since this seems to have been fixed a while ago.

Here are some [docs around it](https://docs.datadoghq.com/serverless/guide/opentelemetry/).

If there is any concern, or you are stuck instrumenting your resources with OTel and the Datadog Extension. Feel free to [create a ticket on our support page](https://help.datadoghq.com/hc/en-us/requests/new)!

Feel free to re-open if there's any issues or concerns.
