### ISSUE TITLE
Add Support For Alpine Linux

### ISSUE THREAD

**Issue by lonnylot** [DataDog/datadog-lambda-extension#112]
Per discussion in slack with Maxime David this extension does not currently support Alpine Linux.

Unsure of why this is, but let me know if there is anything I can do to help get this working.

**Comment by tianchu** [comment]
@maxday any known workaround?

**Comment by thedavl** [comment]
Hi @lonnylot, we've released new images of the extension supporting Alpine Linux (`47-alpine` or `latest-alpine`, [see here](https://gallery.ecr.aws/datadog/lambda-extension)). Give them a try, and please let us know if you have any other issues.
