### ISSUE TITLE
v39 causes docker-based lambda to time out

### ISSUE THREAD

**Issue by diraven** [DataDog/datadog-lambda-extension#124]
## Context

* Using docker image based lambda.
* Building said image by copying DataDog lambda extensions layer contents into an image provided by AWS the way [AWS Blogs](https://aws.amazon.com/blogs/compute/working-with-lambda-layers-and-extensions-in-container-images/) and [DataDog documentation](https://docs.datadoghq.com/serverless/installation/python/?tab=containerimage) suggest.
* Not necessarily, but can be related and contribute to the issue: API_KEY in some circumstances is not provided intentionally. Before v39 it caused no problems and worked as expected.

## Problem

* In AWS environment problem manifests itself with as a lambda time out for v39 extensions. v38 extensions work just fine.

### Dockerfile v38

```dockerfile
FROM public.ecr.aws/lambda/python:3.8
COPY --from=public.ecr.aws/datadog/lambda-extension:38 /opt/extensions/ /opt/extensions
```

```bash
docker run -p 9000:8080 -it tmp datadog_lambda.handler.handler
curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
```

Lines in the log that are similar in both v38 and v39 are skipped for brevity.

```
Traceback (most recent call last): Unable to import module 'datadog_lambda.handler': No module named 'datadog_lambda'
^C
02 Mar 2023 06:28:13,954 [WARNING] (rapid) AwaitAgentsReady() = errResetReceived
02 Mar 2023 06:28:13,954 [WARNING] (rapid) Reset initiated: SandboxTerminated
END RequestId: a1a359e3-c551-439a-8fc8-5cf776ec331d
REPORT RequestId: a1a359e3-c551-439a-8fc8-5cf776ec331d  Init Duration: 0.89 ms  Duration: 144255.73 ms  Billed Duration: 144256 ms      Memory Size: 3008 MB    Max Memory Used: 3008 MB
02 Mar 2023 06:28:13,962 [INFO] (rapid) runtime exited
02 Mar 2023 06:28:15,963 [WARNING] (rapid) Killing agent datadog-agent (e552523e-77ad-4423-99e9-6e7ec981c632) which failed to shutdown
```

### Dockerfile v39

The difference here is that it uses v39 image instead of v38.

```dockerfile
FROM public.ecr.aws/lambda/python:3.8
COPY --from=public.ecr.aws/datadog/lambda-extension:39 /opt/extensions/ /opt/extensions
```

```
docker run -p 9000:8080 -it tmp datadog_lambda.handler.handler
```

Lines in the log that are similar in both v38 and v39 are skipped for brevity.

```
2023-03-02 06:30:35 UTC | DD_EXTENSION | ERROR | Unexpected nil instance of the trace-agent
^C
02 Mar 2023 06:31:43,773 [ERROR] (rapid) Init failed error=errResetReceived InvokeID=
02 Mar 2023 06:31:43,773 [WARNING] (rapid) Reset initiated: SandboxTerminated
02 Mar 2023 06:31:43,779 [INFO] (rapid) runtime exited
Mar 2023 06:31:45,780 [WARNING] (rapid) datadog-agent (eaaa4547-4642-43c9-8c75-30e0307101ff) failed to transition to ShutdownFailed: State transition is not allowed (current state: Registered)
02 Mar 2023 06:31:45,781 [WARNING] (rapid) Killing agent datadog-agent (eaaa4547-4642-43c9-8c75-30e0307101ff) which failed to shutdown
```

### Notable difference in logs

* v39 does not attempt to invoke the handler and does not output "handler not found" error.
* v39 does not output usual `END RequestId:` and `REPORT RequestId:` log lines denoting lambda execution completion.

### Additional notes

* v39 is missing from releases: https://github.com/DataDog/datadog-lambda-extension/releases
* Diff with v38: https://github.com/DataDog/datadog-lambda-extension/compare/v38...v39

Any insight or ideas as to how to work around the issue are appeciated.

**Comment by maxday** [comment]
v40 should fix that! let us know if this is not the case

**Comment by diraven** [comment]
It seems to indeed have the problem resolved. Thank you.
