### ISSUE TITLE
Logged exception is split per line resulting in multiple log entries in DD

### ISSUE THREAD

**Issue by ovidiu-travelperk** [DataDog/datadog-lambda-extension#141]
Hello,

We switched our lambda function running in AWS from a zip lambda to a docker image.
We followed the setup instructions from https://docs.datadoghq.com/serverless/installation/python/?tab=containerimage

But now for error entries logged with `exc_info=` we get these multiple entries in DD, like it's being split per line instead of having a single entry as expected - see the attached image

All those entries in the middle are actually the result of a single `logger.error` call

<img width="1346" alt="Screenshot 2023-05-09 at 17 44 59" src="https://github.com/DataDog/datadog-lambda-extension/assets/63507619/873589f6-7e7b-4b4e-89ba-d4ef268ce30a">

Any idea on what might cause this?

**Comment by IvanTopolcic** [comment]
Hey! Thanks for the report and sorry for the late response :-)

Just want to say that this is an issue that we're aware of and that we'll hopefully have a fix out soon!

**Comment by alexgallotta** [comment]
The issue has been address in version 1.1.3 https://hub.docker.com/r/datadog/serverless-init
> Fixes an issue with log line parsing in the agent that would lead to duplicated, truncated, or missing logs sometimes.
