### ISSUE TITLE
Extension size causing lambda to exceed size limit

### ISSUE THREAD

**Issue by mbrmchll** [DataDog/datadog-lambda-extension#143]
We are trying to use this extension for our lambdas, but getting a size limit error. The extension appears to include the folder listed below, which when I pull the code down locally, is showing 163MB. The entire code base extracted is only 164 MB, so this seems to be taking up the bulk of the size. Just going based on the name of the folder, but should this folder be included in the extension? 

..\datadog-lambda-extension-main\datadog-lambda-extension-main\scripts\go-binsize-viz\example-data

We are using version 43 and 44 currently and seeing the same results in both. 

Looks like this might have been reported before, but closed on issue #79 , but there was no resolution.

**Comment by astuyve** [comment]
Hey @mbrmchll - thanks so much for reaching out!

Another user [ran into this accidentally](https://github.com/DataDog/datadog-lambda-extension/issues/79) as they downloaded the release from github's zip archive, which contains all the source code, scripts, etc (and not the compiled version of the lambda extension which is published as a lambda layer).

Our extension is roughly 38mb when the compiled version is applied as a lambda layer, you can verify this yourself using the aws cli as documented [here](https://docs.datadoghq.com/serverless/guide/serverless_package_too_large/)
```
aws lambda get-layer-version \
  --layer-name arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension \
  --version-number 44
  ```
  
With 44, I see:
<img width="750" alt="image" src="https://github.com/DataDog/datadog-lambda-extension/assets/1598537/62872424-529f-42e1-9e24-7b0fd129c2c4">

Can you clarify how you're installing the extension? Are you running into size errors when deploying to Lambda?

Thanks!

**Comment by mbrmchll** [comment]
> Hey @mbrmchll - thanks so much for reaching out!
> 
> Another user [ran into this accidentally](https://github.com/DataDog/datadog-lambda-extension/issues/79) as they downloaded the release from github's zip archive, which contains all the source code, scripts, etc (and not the compiled version of the lambda extension which is published as a lambda layer).
> 
> Our extension is roughly 38mb when the compiled version is applied as a lambda layer, you can verify this yourself using the aws cli as documented [here](https://docs.datadoghq.com/serverless/guide/serverless_package_too_large/)
> 
> ```
> aws lambda get-layer-version \
>   --layer-name arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension \
>   --version-number 44
> ```
> 
> With 44, I see: <img alt="image" width="750" src="https://user-images.githubusercontent.com/1598537/247242645-62872424-529f-42e1-9e24-7b0fd129c2c4.png">
> 
> Can you clarify how you're installing the extension? Are you running into size errors when deploying to Lambda?
> 
> Thanks!

We are referencing the extension as a layer on our lambda as follows:

```
Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Extension:44
        - !Sub arn:aws:lambda:${AWS::Region}:464622532012:layer:dd-trace-dotnet:8
```

We were understanding that we needed both the Datadog-Extension and the dd-trace-dotnet layers, but maybe the trace extension is causing the problem. Are both needed or do we only need the Datadog-Extension?

**Comment by astuyve** [comment]
For APM tracing they are both needed, but the dotnet tracing layer is 28mb, so the total size is around 66mb:
![image](https://github.com/DataDog/datadog-lambda-extension/assets/1598537/fa9e7fae-e1da-4475-b2c7-b02684e58acf)

Can you confirm that your own code plus 66mb is more or less than the 250mb limit?

Thanks!

**Comment by mbrmchll** [comment]
> For APM tracing they are both needed, but the dotnet tracing layer is 28mb, so the total size is around 66mb: ![image](https://user-images.githubusercontent.com/1598537/247291374-fa9e7fae-e1da-4475-b2c7-b02684e58acf.png)
> 
> Can you confirm that your own code plus 66mb is more or less than the 250mb limit?
> 
> Thanks!

The biggest lambda we have in the project that's failing with the size limit error is 59.4 MB, so that including the layers should not be exceeding 250 MB. 

The errors we are getting are similar to:

"Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 270858104 bytes. (Service: Lambda, Status Code: 400..."

**Comment by astuyve** [comment]
Ah that error seems familiar - are you using the Serverless Framework to build and package your service?

**Comment by mbrmchll** [comment]
> Ah that error seems familiar - are you using the Serverless Framework to build and package your service?

No, we are not using Serverless Framework to build and package.

**Comment by astuyve** [comment]
Okay - something is off here, as 59.4 + 66 is still well under the limit, but somehow that project adds up to 270mb. I'm not sure I can help more in this issue as we can both confirm the size of these libraries are not in fact 163mb.

Can you open a support ticket with Datadog so that we can see the combined deployment package and identify what's contributing to this issue?

Thanks!
