### ISSUE TITLE
How to bundle when `addLayers: false` 

### ISSUE THREAD

**Issue by vieirai** [DataDog/datadog-lambda-extension#161]
The [docs](https://docs.datadoghq.com/serverless/libraries_integrations/macro/) say: 
```
When false, you must include the Datadog Lambda library in your functions’ deployment packages.
```

But there are no instructions on how to actually do this. I tried adding `import "datadog-lambda-js";` to the top of my handlers, so the datadog libs would get bundled (and they did), but that didn't work.

---

Then after browsing through your repos, I came upon [this](https://github.com/DataDog/serverless-plugin-datadog/blob/dae5a0aae8404a3062877dc1194d01f47503dfc2/src/wrapper.ts#L15): 
```js
export const jsHandler = "node_modules/datadog-lambda-js/dist/handler.handler";
```

So I assumed, I'd have to add the entire folder on that specific location, but that didn't work either as it then started throwing errors as it was missing other libraries (`Error: Cannot find module 'hot-shots'`).

So, how are we supposed to "include the Datadog Lambda library in your functions' deployment packages"?

## why?

Having to exclude these libraries from the bundler, makes our functions break when trying to run them locally with `sam local start-api`, so we'd have to always comment the `exclude` rule just to run them locally.
Also I thought that by using our bundler (`esbuild`), we should be able to get better minification and reduce the overall package size.

**Comment by astuyve** [comment]
Hi @vieirai, thanks for reaching out!

You're likely missing the `dd-trace` dependency, which uses `hot-shots`.

If you'd like to use the npm packages instead of Lambda Layers, you'll need to follow the `custom` installation option, following the `Option B` guide [in the documentation](https://docs.datadoghq.com/serverless/installation/nodejs/?tab=custom).

`npm install datadog-lambda-js dd-trace`

Please let me know if this helps.
Thanks!

**Comment by vieirai** [comment]
Hi @astuyve , thank you for looking into this.

So, after playing around with the `Custom` installation option, I ended up applying the datadog wrapper around my handler and adding the layer explicitly as per the docs.
This way I let my bundler package the and tree shake the libraries and then the extension deals with the logs.

I still think the documentation around the `addLayers` toggle on the SAM macro is misleading though, as the only way to bring the libraries in myself, was _not to use the macro_.

**Comment by astuyve** [comment]
Thanks for the note!

If you wrap the handler yourself using the `datadog` method, then there is less of a reason to use the SAM macro. But the macro acts to redirect the handler (which doesn't require the `datadog` method be explicitly called), which makes it still useful when paired with `addLayers: false`.

Either way, glad you got this sorted out!
Thanks,
AJ
