### ISSUE TITLE
Random logging duplication 

### ISSUE THREAD

**Issue by stasOR41k** [DataDog/datadog-lambda-extension#168]
I'm using the latest(48) version of the DataDog Lambda Extention layer with the .NET 7 AOT function to send logs to the DataDog.
The issue is that I have duplicate logs with the same request_id for some requests.
CloudWatch shows logs correctly. No DataDog Forwarder is configured to send logs to the DataDog. No dd-tracer layer is installed as it is not compatible with the .NET AOT.
Does anyone have an idea what is the issue?

**Comment by IvanTopolcic** [comment]
Have you been seeing this on a previous version? And would you be able to provide the logs, with DD_LOG_LEVEL set to debug?

**Comment by stasOR41k** [comment]
Good point, thank you! Found an interesting moment in the duplicated request logs. It is trying to send logs after the REPORT log and facing the issue
`UTC | DD_EXTENSION | WARN | Could not send payload: Post "https://http-intake.logs.datadoghq.com/api/v2/logs": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Comment by duncanista** [comment]
Hey @stasOR41k,

Are you still getting this issue with our latest version? We believe starting v50+, something in AWS side changed it was fixed, now our extension is in parity with CloudWatch. Let me know if this issue still persist. I will close it for now, but please feel free to re-open if this persists with the latest versions, or if you have any other questions! 🙇🏽

**Comment by Onesco** [comment]
@duncanista thanks for the feedback, had the same issue while using the Datadog lambda extension version 48 and will give feedback if it gets resolved.
