### ISSUE TITLE
Node 20 support

### ISSUE THREAD

**Issue by sixfootsixdesigns** [DataDog/datadog-lambda-extension#184]
Hello, we are looking to upgrade our lambdas to node 20 but are currently blocked by this extension not supporting node 20. 
It looks like the node layer version `100` added support for node 20 but when using the latest version `51` of the extension layer, the layers are not being added to our function.

**Comment by astuyve** [comment]
Hi @sixfootsixdesigns, thanks for reaching out!

I'm not sure I understand your question, the lambda layer provided by [dd-lambda-js](https://github.com/DataDog/datadog-lambda-js) is entirely independent of the Datadog Lambda extension provided by this project.

Neither layer adds the other.

Instead, development tools like our serverless framework plugin, cdk construct, or cloudformation macro will apply one or more layers depending on the configuration.

Depending on the tool you're using, you may need to upgrade the tool or follow along an open issue until support is added:
https://github.com/DataDog/serverless-plugin-datadog
https://github.com/DataDog/datadog-cdk-constructs
https://github.com/DataDog/datadog-cloudformation-macro
https://github.com/DataDog/datadog-ci

Thanks!

**Comment by sixfootsixdesigns** [comment]
looking at this file: https://github.com/DataDog/datadog-lambda-extension/blob/main/build-tools/src/commands/deploy_function_command.rs#L172 there is no support for the nodejs20.x runtime. So when using this extension, the layers are not added to the lambda

**Comment by astuyve** [comment]
Hi, sorry for the confusion.

The code in this repository (including what you've linked to) is not part of our extension. Instead these are build tools we use to compile and release our extension. The contents of the `build-tools` directory is only used for a github workflow we use in this project for testing new release candidates.

Our extension code lives here: https://github.com/DataDog/datadog-agent/tree/main/pkg/serverless
The extension logic is completely independent of any runtime. It doesn't add layers at all on its own.

We do that with IAC integrations. Depending on your chosen infrastructure-as-code integration, you may need to upgrade so you can use node20 with Datadog.

Please let me know if you have any questions.
Thanks!

**Comment by sixfootsixdesigns** [comment]
ahh i got crossed up. the issues was with [datadog-cdk-constructs](https://github.com/DataDog/datadog-cdk-constructs) and looks like 2.10.0 adds the support that was missing. Thanks!
