### ISSUE TITLE
Logs from the runtime logger were not forwarded in python lambda handler

### ISSUE THREAD

**Issue by gnoluna** [DataDog/datadog-lambda-extension#185]
Hi there, 

I followed the lambda extension for container image [guide](https://docs.datadoghq.com/serverless/aws_lambda/installation/python/?tab=containerimage) and still couldn't get the log forwarded.

### Environment setup
- Lambda is using an image where I have the datadog extension copied from the public datadog ECR.
- The handler is written in Python and I have `datadog-library` installed
- Architecture is x86_64

### What is working so far
- I have metrics, traces, sketches forwarded successfully can can be seen from the Serverless panel. So I suppose there's no connection/configuration issue.
- I've set `DD_SERVERLESS_FLUSH_STRATEGY = "periodically,100"` and it works as expected
- I've set `DD_LOG_LEVEL=debug` to observe the debug logs in the cloud watch group. From the logs it seems that the `log_agent` is working fine.
```
2023-11-29 14:35:35 UTC | DD_EXTENSION | INFO | Triggering a flush in the logs-agent
2023-11-29 14:35:35 UTC | DD_EXTENSION | DEBUG | Flush in the logs-agent done.
2023-11-29 14:35:35 UTC | DD_EXTENSION | DEBUG | Finished logs flush that was started at time 1701268535
2023-11-29 14:35:35 UTC | DD_EXTENSION | DEBUG | Hit on the serverless.Flush route.
```

### What doesn't work
Looks like the logs were not forwarded to datadog. In the function's `Logs` tab, nothing but `No logs found for this function` is shown.

Any help would be greatly appreciated. 🙏

**Comment by astuyve** [comment]
Hi @gnoluna, sorry for the delay I think this library mainly holds our release software for the extension and not our actual code so it's not checked as frequently as it could be.

Please reach out to support directly, as likely they'll collect logs and serverless flare data from your function which is best done on a non-open channel.
support@datadoghq.com

thanks!
