### ISSUE TITLE
Arm64 support. Multi-arch image.

### ISSUE THREAD

**Issue by SergeStrashko** [DataDog/datadog-lambda-extension#190]
AWS Public ECR contains the DD [lambda-extension](https://gallery.ecr.aws/datadog/lambda-extension) available only for `x86_64`
Same time the  [datadog/agent](https://gallery.ecr.aws/datadog/agent) is available for `arm64` as well

Having Datadog/lambda-extension available for `arm64` seems quite reasonable.

**Comment by purple4reina** [comment]
Hi @SergeStrashko. I have tested this locally, it seems an arm64 image is in fact available. It's just not listed on the ecr webpage for some reason. Are you seeing something different?

**Comment by SergeStrashko** [comment]
> It's just not listed on the ecr webpage for some reason. Are you seeing something different?

This is exactly the issue.
I believe that 99.99% of `datadog/lambda-extension` usages are like the following:

```
COPY --from=public.ecr.aws/datadog/lambda-extension:{version} /opt/. /opt/
```

**Comment by duncanista** [comment]
Hey @SergeStrashko,

Our team doesn't control the image description, yet I asked them to please update it to include ARM64.

I'm going to close this issue, as it now appears in https://gallery.ecr.aws/datadog/lambda-extension
