### ISSUE TITLE
Unknown environment variable: DD_SERVERLESS_FLUSH_STRATEGY

### ISSUE THREAD

**Issue by Vladikamira** [DataDog/datadog-lambda-extension#196]
datadog lambda extension version `53` throws a warning that variable `DD_SERVERLESS_FLUSH_STRATEGY` is unknown, however, the var is properly parsed and applied 

<img width="1100" alt="Screenshot 2024-02-21 at 21 34 06" src="https://github.com/DataDog/datadog-lambda-extension/assets/5423271/5ec876a4-8567-4d29-ac92-713404b752d6">

**Comment by duncanpharvey** [comment]
Hi @Vladikamira, thanks reporting this! I created an internal ticket to address this issue. We'll follow up here once we've deployed a fix.

**Comment by duncanpharvey** [comment]
Hi @Vladikamira, this issue is fixed in [v56](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v56 ) of the Datadog Lambda Extension!
