### ISSUE TITLE
`DD_APM_ENABLED=false` in Lambda ENV causes `Extension.Crash`

### ISSUE THREAD

**Issue by MarkusSintonen** [DataDog/datadog-lambda-extension#263]
Having `DD_APM_ENABLED=false` in Lambda ENV and using `arn:aws:lambda:{region}:464622532012:layer:Datadog-Extension:57` extension layer causes the Lambda to crash. Then getting only two lines of not very informative messages:
```
@message | RequestId: xyz Error: exit code 0 Extension.Crash
@message | INIT_REPORT Init Duration: 4447.52 ms	Phase: invoke	Status: error	Error Type: Extension.Crash
```

Having this ENV should not cause a complete crash of the Lambda. It should atleast give a message explaining whats wrong.

**Comment by purple4reina** [comment]
Hey @MarkusSintonen, thanks for reporting this. I've been able to reproduce the crash and am looking into it more closely now.
