### ISSUE TITLE
Lambda execution does not properly completes after upgrading from v58 to v59

### ISSUE THREAD

**Issue by santiagoaguiar** [DataDog/datadog-lambda-extension#308]
After switching from v58 to v59 of the lambda extension, we noticed that a number of our lambdas started to run until timeout, completing just before the timeout (no error). Once we rollbacked to v58, the issue disappeared.

The behavior we observed is that we emitted a log at the end of the execution, which for example occurred after 1-3 minutes, and 12 minutes later, when we are about to time out at 15 minutes (e.g. at 899981.32ms), the lambda completes without error and emits the END/REPORT logs.

The two lambdas that caused issues for us where regularly scheduled to run every 1 and 3 minutes respectively, with a max concurrency of 1, and in few occasions are throttled due to the concurrency limit.

The issue was consistent once it started occurring, but we had periods of 1-2 hours were it looked resolved, until it triggered again and remained in this state for some hours. We are relatively certain the issue disappeared after a cold start, but then triggered again after the lambda processed some requests.

Using a docker based lambda based on python:3.12-alpine3.19, ddtrace==2.8.0, django==4.2.11 stack

**Comment by santiagoaguiar** [comment]
We also noticed that we only get the first 1k logs from the lambda into DataDog, while  CloudWatch had many more.

**Comment by hghotra** [comment]
Hi @santiagoaguiar, thanks for reporting this issue - someone from the team will take a look at it shortly. In the meantime, can you post the shortest version of the lambda function that causes this issue to help reproduction on our end?

**Comment by DylanLovesCoffee** [comment]
Hey @santiagoaguiar would it be possible for you to send a Serverless flare to Datadog from the Lambda functions in question? https://docs.datadoghq.com/serverless/libraries_integrations/cli/#troubleshooting-lambda-instrumentation

**Comment by DylanLovesCoffee** [comment]
Closing this as we believe we've found the issue and merged a fix.
