### ISSUE TITLE
Versions > 60 breaks local image testing

### ISSUE THREAD

**Issue by jedschneider** [DataDog/datadog-lambda-extension#347]
**Problem:** Newer versions of the extension fail to run cleanly and change the observable STDOUT stream when testing the images locally or in CI.

We use the process described [here](https://docs.aws.amazon.com/lambda/latest/dg/python-image.html) - "(Optional) Test the image locally" which describes how to start and use curl to invoke the function in a local docker container. We've found this process helps identify problems at the OS and extension level much before we try to debug live in AWS. However, the most recent versions of the datadog extension seem to swallow the stdout stream which is breaking our use of these "smoke tests" in our CI pipeline.

It should be noted that the v62 extension seems to run as expected in a running aws lambda, so this seems to be a configuration or difference in the local booting of the container.

**Expected Behavior:** The datadog extension does not modify the observable behavior of the lambda invocation, or a configuration flag is provided that allows the STDOUT to be re-routed for evaluation.

**Steps to replicate:**

An example application can be made by creating a folder with three items:
1. app.rb
2. Dockerfile.working (uses extension pinned at v60)
3. Dockerfile.broken (uses extension pinned at v62)

`app.rb` contains the following:

```ruby
def handler(event:, context:)
  'OK'
end
```

A working Dockerfile uses version 60 of the datadog extension:

```dockerfile
# Dockerfile.working
FROM public.ecr.aws/lambda/ruby:3.2

RUN yum update -y --security
RUN yum install -y gcc git make

COPY --from=public.ecr.aws/datadog/lambda-extension:60 /opt/. /opt/

COPY app.rb ${LAMBDA_TASK_ROOT}

CMD [ "app.handler" ]
```

A Dockerfile that illustrates the change in behavior uses a stable release >60, at the time of writing this issue, is 62.

```dockerfile
# Dockerfile.broken
FROM public.ecr.aws/lambda/ruby:3.2

RUN yum update -y --security
RUN yum install -y gcc git make

COPY --from=public.ecr.aws/datadog/lambda-extension:62 /opt/. /opt/

COPY app.rb ${LAMBDA_TASK_ROOT}

CMD [ "app.handler" ]
```

**Demonstrating the change in behavior.**

### Baseline v60

Build and start the image

```
docker build --tag datadog:working -f Dockerfile.working .
docker run -p 9001:8080 -t datadog:working
```

Invoke the image with curl and observe output from both terminals:

docker:

```
START RequestId: e1e08a2f-bf73-4561-b803-1b0b15aad027 Version: $LATEST
05 Aug 2024 15:57:08,614 [INFO] (rapid) INVOKE START(requestId: 6ac35e26-b71e-4817-89ff-673ee7e2fb81)
05 Aug 2024 15:57:08,619 [INFO] (rapid) INVOKE RTDONE(status: success, produced bytes: 0, duration: 4.935000ms)
END RequestId: 6ac35e26-b71e-4817-89ff-673ee7e2fb81
REPORT RequestId: 6ac35e26-b71e-4817-89ff-673ee7e2fb81	Duration: 5.36 ms	Billed Duration: 6 ms	Memory Size: 3008 MB	Max Memory Used: 3008 MB	
```

curl:

```
% curl -XPOST "http://localhost:9001/2015-03-31/functions/function/invocations" -d '"SMOKE TEST"'
"OK"%
```

### v62

Build and start the image

```
docker build --tag datadog:broken -f Dockerfile.broken .
docker run -p 9000:8080 -t datadog:broken
```

Invoke the image with curl and observe output from both terminals:

docker:

```
START RequestId: 56c2cb08-8391-41d8-a4e1-2324df8927d8 Version: $LATEST
05 Aug 2024 15:59:30,217 [INFO] (rapid) INIT START(type: on-demand, phase: init)
05 Aug 2024 15:59:30,221 [WARNING] (rapid) First fatal error stored in appctx: Extension.Crash
05 Aug 2024 15:59:30,221 [WARNING] (rapid) Process extension-datadog-agent-1 exited: signal: trace/breakpoint trap
05 Aug 2024 15:59:30,221 [INFO] (rapid) INIT REPORT(durationMs: 4.669000)
05 Aug 2024 15:59:30,221 [ERROR] (rapid) Init failed InvokeID= error=signal: trace/breakpoint trap
05 Aug 2024 15:59:30,222 [WARNING] (rapid) Shutdown initiated: spindown
05 Aug 2024 15:59:30,222 [WARNING] (rapid) The runtime was not started.
05 Aug 2024 15:59:30,222 [INFO] (rapid) Waiting for runtime domain processes termination
05 Aug 2024 15:59:30,222 [INFO] (rapid) INIT START(type: on-demand, phase: invoke)
05 Aug 2024 15:59:30,222 [INFO] (rapid) INIT REPORT(durationMs: 0.158000)
05 Aug 2024 15:59:30,222 [INFO] (rapid) INVOKE START(requestId: cd1c80d6-5ef0-4a57-81db-667acaab27d6)
05 Aug 2024 15:59:30,222 [ERROR] (rapid) Invoke failed error=ErrAgentNameCollision InvokeID=cd1c80d6-5ef0-4a57-81db-667acaab27d6
05 Aug 2024 15:59:30,222 [ERROR] (rapid) Invoke DONE failed: Sandbox.Failure
05 Aug 2024 15:59:30,222 [WARNING] (rapid) Reset initiated: ReleaseFail
05 Aug 2024 15:59:30,222 [WARNING] (rapid) The runtime was not started.
05 Aug 2024 15:59:30,222 [WARNING] (rapid) Agent datadog-agent (24274ec6-bc73-43da-9e66-3f5dd973d006) failed to launch, therefore skipping shutting it down.
05 Aug 2024 15:59:30,222 [INFO] (rapid) Waiting for runtime domain processes termination
```

Note: it appears the extension is not booting or working correctly.

curl:

```
% curl -XPOST "http://localhost:9001/2015-03-31/functions/function/invocations" -d '"SMOKE TEST"'
```

(note that the stdout is not receiving the expected `"OK"` text back from the handler.

**Comment by astuyve** [comment]
Hi, please add `AWS_DEFAULT_REGION` as an environment variable as per [this discussion](https://github.com/DataDog/datadog-lambda-extension/issues/331#issuecomment-2259089471). This variable is expected to be set in Lambda but not present in the runtime interface emulator.

We have merged a fix for this and will release it early this week. Note that due to the lack of telemetry API, no logs or APM spans will be generated.

Thanks!

**Comment by jedschneider** [comment]
I'm confirming that setting the env var does indeed fix the output! Thanks for the quick reply, this unblocks us and we'll look forward to the next release. Cheers!

```
% docker run -e AWS_DEFAULT_REGION=us-east-1 -p 9000:8080 -t datadog:broken
06 Aug 2024 15:35:34,006 [INFO] (rapid) exec '/var/runtime/bootstrap' (cwd=/var/task, handler=)
START RequestId: 8b51cc92-af81-4f25-89ca-90d77cf27f99 Version: $LATEST
06 Aug 2024 15:36:17,349 [INFO] (rapid) INIT START(type: on-demand, phase: init)
{"DD_EXTENSION_FAILOVER_REASON":"extension_version"}
2024-08-06 15:36:17 UTC | DD_EXTENSION | ERROR | No API key configured
2024-08-06 15:36:17 UTC | DD_EXTENSION | ERROR | Can't start the Datadog extension as no API Key has been detected, or API Key could not be decrypted. Data will not be sent to Datadog.
06 Aug 2024 15:36:17,432 [INFO] (rapid) External agent datadog-agent (0807b1e5-a107-490c-a23e-09ac693be404) registered, subscribed to [INVOKE SHUTDOWN]
06 Aug 2024 15:36:17,432 [INFO] (rapid) Starting runtime without AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN , Expected?: false
06 Aug 2024 15:36:17,532 [INFO] (rapid) INIT RTDONE(status: success)
06 Aug 2024 15:36:17,532 [INFO] (rapid) INIT REPORT(durationMs: 182.612000)
06 Aug 2024 15:36:17,532 [INFO] (rapid) INVOKE START(requestId: 36ee0774-5f05-45c5-b117-d0b8b12f7b9a)
06 Aug 2024 15:36:17,533 [INFO] (rapid) INVOKE RTDONE(status: success, produced bytes: 0, duration: 0.916000ms)
END RequestId: 36ee0774-5f05-45c5-b117-d0b8b12f7b9a
REPORT RequestId: 36ee0774-5f05-45c5-b117-d0b8b12f7b9a	Init Duration: 0.19 ms	Duration: 183.88 ms	Billed Duration: 184 ms	Memory Size: 3008 MB	Max Memory Used: 3008 MB	
````

**Comment by astuyve** [comment]
Great! Sorry about that interruption. I'll close this ticket once I release v63.

**Comment by duncanista** [comment]
Hey @jedschneider,

@astuyve has released version [v63](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v63), please let us know if you have any issues!

I'm gonna close this issue, but feel free to re-open if issue persist.
