### ISSUE TITLE
Extension.Crash Error with v62 on Java Lambda

### ISSUE THREAD

**Issue by JosephWitthuhnTR** [DataDog/datadog-lambda-extension#351]
We have noticed that v60 works just fine, but v62 is broken. We did not try with version 61, since the releases page explicitly calls that one out as broken.

Our lambda crashes during initialization with just this output:
```
2024-08-01T14:38:27.251-05:00 INIT_START Runtime Version: java:17.v29	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:10d20d62ff98ec8d0d7359298e7d1b29191500e2cc39ea7a1312f16faef90e83
2024-08-01T14:38:27.312-05:00 EXTENSION	Name: datadog-agent	State: Started	Events: []
2024-08-01T14:38:27.312-05:00 INIT_REPORT Init Duration: 60.90 ms	Phase: init	Status: error	Error Type: Extension.Crash
```

Our environment is a Java 17 lambda with these variables set (I've obscured the values of the DD_* ones, which I believe shouldn't matter):

```
AWS_LAMBDA_EXEC_WRAPPER=/opt/datadog_wrapper
DD_API_KEY_SECRET_ARN=***
DD_ENV=***
DD_SERVICE=***
DD_VERSION=***
```

And are using these two layers:
```
arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:62
arn:aws:lambda:us-east-1:464622532012:layer:dd-trace-java:15
```

This is following the instructions here:
https://docs.datadoghq.com/serverless/aws_lambda/installation/java/?tab=custom

**Comment by astuyve** [comment]
Hi @JosephWitthuhnTR - thanks for reaching out, I'll take a look right away

**Comment by astuyve** [comment]
Hi @JosephWitthuhnTR I'm having ab it of trouble reproducing this one.
I've created a demo function using java 17 and extension 62 with dd-trace-java 15 as per your instructions. I've set similar tags and env variables:
<img width="1499" alt="image" src="https://github.com/user-attachments/assets/083f5752-1c0a-45d1-b208-722095e63d6d">

<img width="796" alt="image" src="https://github.com/user-attachments/assets/4e91717f-9961-4fb9-a6b1-3c02a743f3a1">

But the logs I get seem to be fine:
<img width="2705" alt="image" src="https://github.com/user-attachments/assets/f675022c-137e-4125-9b22-40f5e6a34add">

Can you confirm which architecture you're using, and any other information which may help me reproduce this crash? Would you mind opening a support ticket so we can share other debug information more securely? You can attach this github issue and specifically mention this escalate to me to move things along.

Thanks!

**Comment by JosephWitthuhnTR** [comment]
Thanks for the quick reply!

Our architecture is x86_64.

Other relevant details:
- Our lambda layers are declared in the opposite order from your screenshot. I know order of layers does matter in Lambda (but may not, depending on the contents). Do we have these declared in the wrong order, or is there no "right" order?
- We are using Lambda SnapStart. This happens when we publish a new version (SnapStart does that initialization step before taking it's image). Eventually we get a message like this: `Couldn't create version X of function XXXXXX: An error occurred during function initialization.` At that point, the logs I shared above are visible in CloudWatch. So we aren't yet trying to execute the function, just create a new version for SnapStart to initialize.
- Our lambda is attached to subnets on a VPC.

**Comment by JosephWitthuhnTR** [comment]
Never mind on the layer order bit. This impacts multiple lambdas of ours, and we have examples of ones where the layers are in both orders that are not working.

**Comment by astuyve** [comment]
Yeah layer merge order can really [wreck things](https://aaronstuyvenberg.com/posts/why-you-should-not-use-lambda-layers) if you're sharing libraries, but in this case the extension and java tracer does not conflict.

Can you set `DD_LOG_LEVEL: debug` and see if anything changes? If you remove snapstart on a test function, does the problem go away?

I'll attempt to add snapstart and see.

**Comment by astuyve** [comment]
Okay I can reproduce it when enabling snapstart
<img width="1496" alt="image" src="https://github.com/user-attachments/assets/e0d645b7-0354-4801-9d7b-d83128fbc3a9">

Thanks @JosephWitthuhnTR, will investigate this further.

**Comment by astuyve** [comment]
Hi @JosephWitthuhnTR I've reproduced this issue with 62.

The good news is the fix for 63 is already merged, it seems one of the AWS secret environment variables we depend on wasn't present during snapstart initialization. This [pr](https://github.com/DataDog/datadog-lambda-extension/pull/342/files) fixes it:
<img width="728" alt="image" src="https://github.com/user-attachments/assets/36433995-3677-4961-a234-c72c2b84a795">
I will let you know when 63 is released.

Thanks!

**Comment by astuyve** [comment]
Hi @JosephWitthuhnTR - this should be fixed in [63](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v63).

Please feel free to re-open if this issue persists for you, thanks again!
