### ISSUE TITLE
Setting logLevel causes DD_EXTENSION logs to appear

### ISSUE THREAD

**Issue by trevor-e** [DataDog/datadog-lambda-extension#364]
Hi,

I'm trying to set `logLevel: INFO` in my datadog configuration to exclude debug logs from being ingested, but this is causing a weird behavior where now I see a bunch of `DD_EXTENSION` logs: 

<img width="1211" alt="Screenshot 2024-08-19 at 12 11 35 PM" src="https://github.com/user-attachments/assets/fd9a2698-68f3-4c02-89c2-21532739e2ff">

These logs never previously showed up, and they are happening quite frequently. I don't see a way to turn them off.

**Comment by duncanista** [comment]
Hey @trevor-e,

It seems that a recent change in [DataDog/datadog-agent](https://github.com/DataDog/datadog-agent) has updated how the log level is being read. Sorry for the inconvenience. I'm going to update this logs to Debug, and follow up with the agent team to ask about the change.

**Comment by duncanista** [comment]
Hey @trevor-e,

We are fixing this is in the next version!

**Comment by duncanista** [comment]
Hey @trevor-e,

Sorry for the delay, this should have been fixed on latest v65!
