### ISSUE TITLE
Extension crashing

### ISSUE THREAD

**Issue by mallyx3** [DataDog/datadog-lambda-extension#39]
Hello. My lambda is deployed with the datadog lambda extension.

My lambda intermittently crashes here and there and I believe its because of the extension crashing.

The logs are available here:
![image](https://user-images.githubusercontent.com/8528854/141388666-efbf9640-4d1b-4de5-98c3-371f6a05a400.png)
![image](https://user-images.githubusercontent.com/8528854/141388680-fcb738fc-3d4e-4016-9428-01227038d54c.png)

**Comment by maxday** [comment]
Hi, which version of the extension are you running? 
Would it be possible to share full debug log by setting the `DD_LOG_LEVEL` environment variable to `DEBUG`
