### ISSUE TITLE
Cold start and Duration times

### ISSUE THREAD

**Issue by T-Klug** [DataDog/datadog-lambda-extension#429]
The first number is durationMs - and the second is initDurationMs

![Image](https://github.com/user-attachments/assets/55e84b9a-1fd4-4c05-84dc-8d6d0d065780)

Even with the experimental flag, these numbers are pretty abysmal for cold starts and even durations (due to the flush) 

Is the only solution to this writing a delivery mechanism ourselves? What other options exist because this is a big hit on performance.

**Comment by purple4reina** [comment]
Hey @T-Klug, Thanks for reaching out. Can you share with versions of all our layers you are using, including which runtime you're using? I suspect that most of your added init time is coming from the tracing layer, but I can't know for sure unless I get a bit more info about your setup.

**Comment by T-Klug** [comment]
![Image](https://github.com/user-attachments/assets/102437d0-ffe8-4827-a25f-f1407cc6b7dc)
![Image](https://github.com/user-attachments/assets/ae2141cb-f602-4b03-967b-bbb4684a6401)


Using latest nodeLayerVersion 115 and extensionLayerVersion 65

Using node 20 with the CDK NodeJSFunction construct

**Comment by purple4reina** [comment]
Thanks @T-Klug. Can you test with _just_ the extension please, and no tracing layer? To do this, you'll set `addExtension: true` and remove the `nodeLayerVersion: 115`. If you have any datadog references in your code, or have manually added any handler redirection, please remove it for this test.

Datadog's next-gen extension shouldn't add _nearly_ as much overhead as you're seeing, other customers have reported overhead in the 10s of milliseconds range compared with their base implementation. So, I'd like to confirm that this overhead is not actually coming from the extension, but from the tracer.

**Comment by T-Klug** [comment]
![Image](https://github.com/user-attachments/assets/e11725f8-d74c-4f2f-8e41-85711c05d12a)
the type doesn't have addExtension: true and when removing the nodeLayerVersion - the entire handler stops working

**Comment by T-Klug** [comment]
After reviewing your documentation on the CDK - that is not the correct way of running it.

**Comment by T-Klug** [comment]
Marking enableDatadogTracing: false does get us in a bit of a better spot 

![Image](https://github.com/user-attachments/assets/2a17e243-8a46-4e86-9439-c54eaf90e232)

**Comment by T-Klug** [comment]
still a 200ms difference though between the 600ms and 800 ms

**Comment by T-Klug** [comment]
![Image](https://github.com/user-attachments/assets/fe3147d3-acb1-44d4-a443-9668d76c29e8)

**Comment by purple4reina** [comment]
Hi @T-Klug,

My apologies, I told you to use `addExtension` when it should be `addLayers`. Here's how you'll want to configure it to completely remove the datadog node tracing layer.

```ts
const datadog = new Datadog(this, 'Datadog', {
  apiKeySecret: Secret.fromSecretNameV2(this, ‘DatadogApiKey’, ‘DatadogApiKey’),
  addLayers: false,
  enableDatadogLogs: true,
  extensionLayerVersion: 65,
  env: domainName,
});
```

This should remove the `Datadog-Node20-x` tracing layer and no longer apply the handler redirection.

**Comment by T-Klug** [comment]
That still breaks the handlers - even including the datadog-lambda-js within the package json, turning off the addLayers must need additional changes to the handlers or an import I am unaware of. Is there complete documentation about this setup? I don't see a clear path in the documentation describing what you are suggesting. 


![Image](https://github.com/user-attachments/assets/26cab1b5-edbf-401f-a685-2ff8046a180e)

**Comment by purple4reina** [comment]
Can you share with me exactly how you're configuring your functions and how you're adding the datadog instrumentation?

**Comment by T-Klug** [comment]
I tried with and without the package. When I do the setup you suggest, it breaks the handler. 

Here is the setup of the Datadog construct, the add lambda functions, and the env for the lambda itself doing the API gateway. 

![Image](https://github.com/user-attachments/assets/8971ba03-b467-485e-9234-438ab2b12364)

![Image](https://github.com/user-attachments/assets/5348491d-45a4-46f8-8f65-f7c0d6b5dba1)
![Image](https://github.com/user-attachments/assets/e310d0bf-5768-43c2-b3f3-84f94330a387)

**Comment by T-Klug** [comment]
The handler breaks when I change the datadog to addLayer: false and remove the nodeLayerVersion.

**Comment by purple4reina** [comment]
Can you specify the `handler` attr on the contruct props? Like

```ts
const lambdaFunction = new NodejsFunction(this, 'Handler', {
  ...  // as before
  handler: 'handler.handler',  // replace with proper handler value
});
```

Alternatively, you can remove datadog altogether and just add the extension and required env vars manually. Like

```ts
const lambdaFunction = new NodejsFunction(this, 'Handler', {
  ...  // as before
  layers: [
    LayerVersion.fromLayerVersionArn('arn:aws:lambda:<AWS_REGION>:464622532012:layer:Datadog-Extension:65'),  // replace region
  ],
  environment: [
    ...  // as before
    DD_EXTENSION_VERSION: 'next',
    DD_API_KEY: 'api-key',  // replace api key plaintext or use DD_API_KEY_SECRET_ARN
    DD_SERVICE: 'my-cool-service'
    DD_ENV: domainName,
  ],
});
```

**Comment by T-Klug** [comment]
I'm sorry, but that has nothing to do with it. 

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.NodejsFunction.html#handler

It runs just fine without Datadog - and with the setup above. 

Obviously, datadog.addLambdaFunctions is the culprit here, and the datadog v2 construct requires the node layer to present. 


addLayers | add_layers | Whether to add the runtime Lambda Layers or expect the user to bring their own. Defaults to true. When true, the Lambda Library version variables are also required. When false, you must include the Datadog Lambda library in your functions’ deployment packages.
-- | -- | --

This is directly from your documentation. There isn't a clear documented path to what you described - and just throwing random things into the environment isn't working.

**Comment by purple4reina** [comment]
If we can remove the `Datadog-Node20-x` layer from your function, leaving only the `Datadog-Extension-ARM` layer, you should see cold start times in the 10's of milliseconds range.

Recognizing that `datadog.addLambdaFunctions` isn't behaving properly in your case, I recommend removing the datadog construct altogether and adding the extension layer and env vars manually.

**Comment by T-Klug** [comment]
How will it work if we do not have the handler going through the node JS implementation? 

https://docs.datadoghq.com/serverless/aws_lambda/installation/nodejs/?tab=custom

The custom setup itself requires it to pass through the handler. Are you saying the extension arm can be utilized without hooks in the handler, etc.? What would need to be initialized? 

Install the Datadog Lambda library.
Install the Datadog Lambda Extension

Just adding the extension alone wouldn't add any overhead because it would never send anything unless the documentation is incorrect. 

Can you expand on how adding that layer alone would send the logs/metrics/traces?

**Comment by purple4reina** [comment]
The extension works independently of the tracing layers to provide you with enhanced metrics and logs. We do this by tapping into the [AWS Lambda Telemetry API](https://docs.aws.amazon.com/lambda/latest/dg/telemetry-api.html). Adding the tracing layer ("Datadog Lambda Library") is what creates your traces.

The Datadog Extension layer is treated a bit differently by the lambda runtime than the tracing layers. During initialization, the lambda runtime will look through the `/opt/extensions` directory and start each executable found there. This is different from the tracing layers which work essentially the same as mounting a volume.

**Comment by T-Klug** [comment]
I have followed the above and implemented it on one of our lambdas, removing it from the cdk construct. 

Now, the handler fails with "/opt/extensions/datadog-agent: /opt/extensions/datadog-agent: cannot execute binary file"

![Image](https://github.com/user-attachments/assets/6a917d07-3f31-4ff8-952a-5873e9611502)
![Image](https://github.com/user-attachments/assets/4cd6b3a1-23c4-44c8-ab0a-ed31c7ce606c)

**Comment by purple4reina** [comment]
The extension is architecture specific. You need to use the `Datadog-Extension-ARM` version.

**Comment by T-Klug** [comment]
got it Ill give that a go was using the above from your example 

![Image](https://github.com/user-attachments/assets/5bcbffde-c156-4394-9337-164669f413b7)

**Comment by T-Klug** [comment]
That seemed to allow the function to work - however, even with the environment variable to do the logs - it wasn't exporting the logs while tailing

**Comment by T-Klug** [comment]
I will close this - as we are in an accepted range for us with the setup turning off tracing.
