### ISSUE TITLE
public.ecr.aws/datadog/lambda-extension only has ARM images for versions >=11

### ISSUE THREAD

**Issue by someboredkiddo** [DataDog/datadog-lambda-extension#49]
We currently use the datadog-lambda-extension to monitor our containerized x86 architected lambdas (base image is `FROM amazon/aws-lambda-python:3.8`)

We have been successfully following [installation instructions](https://docs.datadoghq.com/serverless/installation/python/?tab=containerimage#install-the-datadog-lambda-extension) to import the lambda extension into our Docker image from `public.ecr.aws/datadog/lambda-extension`

```
COPY --from=public.ecr.aws/datadog/lambda-extension:<TAG> /opt/extensions/ /opt/extensions
```

However, trying to use any lambda-extension version >= 11 currently results in the lambda failing with the below error:
`Error: fork/exec /opt/extensions/datadog-agent: exec format error
Extension.LaunchError`

Running `docker inspect` on the lambda-extension images in `public.ecr.aws/datadog/lambda-extension` reveals that lambda-extension versions 1-10 are `amd64` (x86) while versions >=11 has changed to `arm64`. Guessing this architecture incompatibility between the extension and our lambda is causing the error.

Is there a ecr repo where we can pull x86 compatible lambda-extension images? Also recommend fixing the architecture tags for the public ecr repo.

![image](https://user-images.githubusercontent.com/1919925/151681089-9f1d8389-e71c-4c3d-9cc9-816c9f92225b.png)

**Comment by someboredkiddo** [comment]
Whoops, this is user error, my bad. images >= 11 have both architectures bundled, the default is just arm for >=11.

For others benefits - to make sure the correct `public.ecr.aws/datadog/lambda-extension` image is pulled just make sure to specify your base image's arch when building

ex.
```
docker build --platform "linux/amd64" .
```

I could have confirmed this my pulling the manifest file from the public image
```
docker manifest inspect --verbose public.ecr.aws/datadog/lambda-extension:18
```

Feel free to close this - but might still be worth clarify this gotcha  in the container install documentation on https://docs.datadoghq.com/serverless/installation for engineers like myself who normally look to tagging to take care of different architecture installs.  Did a draft of what this might look like for just the python instructions here - https://github.com/DataDog/documentation/pull/12972

**Comment by nhinsch** [comment]
This issue was discussed here:
https://github.com/DataDog/documentation/pull/12972

The issue was that when a Docker image is built on an ARM-based machine (e.g. a Mac with an Apple Silicon chip), Docker will default to building an ARM image, which won't work properly for a x86_64 Lambda function. The solution was to override the default when building the image.

**Comment by GonzalezAndrew** [comment]
I would like to add a comment for those who might find this issue searching for help. 

I currently build & deploy my lambda containers using Terraform which does not allow me to specify the platform I build the container easily. In order to build the container and pull the appropriate datadog-layer platform, I did the following in the Dockerfile

```
# install datadog lambda extension
FROM --platform=linux/x86_64 public.ecr.aws/datadog/lambda-extension:latest AS dd

# base lambda image
FROM --platform=linux/x86_64 public.ecr.aws/lambda/python:3.9

# copy over the datadog extension into our lambda
COPY --from=dd /opt/extensions/ /opt/extensions

# ensure libs are up to date
RUN : \
    && yum -y update --security \
    && yum clean all \
    && rm -rf /var/cache/yum \
    :

# copy over the lambda code
WORKDIR ${LAMBDA_TASK_ROOT}
COPY ./*.py ${LAMBDA_TASK_ROOT}
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# install the lambda code requirements
RUN : \
    && python3.9 -m pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}" \
    && python3.9 -m pip install datadog-lambda --target "${LAMBDA_TASK_ROOT}" \
    &&:

# set dd extension
CMD ["datadog_lambda.handler.handler"]

```

I'm doing this on a Mac M1 and works great for deploying `x86_64` arch lambdas

**Comment by hakuno** [comment]
> I would like to add a comment for those who might find this issue searching for help.
> 
> I currently build & deploy my lambda containers using Terraform which does not allow me to specify the platform I build the container easily. In order to build the container and pull the appropriate datadog-layer platform, I did the following in the Dockerfile
> 
> ```
> # install datadog lambda extension
> FROM --platform=linux/x86_64 public.ecr.aws/datadog/lambda-extension:latest AS dd
> 
> # base lambda image
> FROM --platform=linux/x86_64 public.ecr.aws/lambda/python:3.9
> 
> # copy over the datadog extension into our lambda
> COPY --from=dd /opt/extensions/ /opt/extensions
> 
> # ensure libs are up to date
> RUN : \
>     && yum -y update --security \
>     && yum clean all \
>     && rm -rf /var/cache/yum \
>     :
> 
> # copy over the lambda code
> WORKDIR ${LAMBDA_TASK_ROOT}
> COPY ./*.py ${LAMBDA_TASK_ROOT}
> COPY requirements.txt ${LAMBDA_TASK_ROOT}
> 
> # install the lambda code requirements
> RUN : \
>     && python3.9 -m pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}" \
>     && python3.9 -m pip install datadog-lambda --target "${LAMBDA_TASK_ROOT}" \
>     &&:
> 
> # set dd extension
> CMD ["datadog_lambda.handler.handler"]
> ```
> 
> I'm doing this on a Mac M1 and works great for deploying `x86_64` arch lambdas

I needed it to run Lambda function on ARM64. But it runs NodeJS instead of. Thank you!
