### ISSUE TITLE
`service` tag is not correctly applied to the lambda function logs (and traces)

### ISSUE THREAD

**Issue by jonathanmorley** [DataDog/datadog-lambda-extension#5]
Reproduction Steps:

1. Create a lambda function with the DD extension, some logs, and a `service` tag.
2. Wait approximately 15m for the AWS integration to pick up the tags of the new lambda function
3. Invoke the lambda

Pull up a log of the invocation from DataDog and export it as JSON. The log will contain `content.tags.service` with the value you provided as a `service` tag, but it will also contain `content.service` and `content.attributes.service` with the the name of the function.

The value of 'service' that DataDog associates with the log is the name of the function, not the one explicitly set as a `service` tag.

**Comment by cinch-toli** [comment]
We have come across something similar. It seems that if you set the env variables on the lambda:

```
DD_SERVICE: '<SERVICE_NAME>'
DD_ENV: '<ENV_NAME>'
```

the service and env tags are applied correctly on spans but not on logs. The [documentation](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=serverlessframework#aws-lambda-functions) for serverless however does discourage using env variables in favour of tags. 

We would prefer if the tags on spans and logs were inherited from the function stack tags if present, or from Lambda function tags if they are overriding the stack tags.

**Comment by IGassmann** [comment]
I believe the latest version "9" solves this issue.

**Comment by maxday** [comment]
Hi, thanks for reporting the issue. This should be fully resolved with the version 10.
Let me know if you still have the issue.

**Comment by maxday** [comment]
Closing this for now, feel free to re-open if your tags are still not correctly applied
