### ISSUE TITLE
Lambda tags are not passed on to datadog

### ISSUE THREAD

**Issue by olup** [DataDog/datadog-lambda-extension#53]
Tags added on my lambdas are not passed on to datadog. I have setup `env`  `version` and `service` in all my lambdas, but logs don't show those (or others I might have added on top). Setting env var (ie. `DD_ENV`) works, but I'd rather see my tags in the logs.

Is there a prameter I have missed ?

I am using version 21 of the extension.

Cheers.

Edit: I use seilf made pipeline using pulumi to build and deploy lambda, add layers, tags, etc...

**Comment by tianchu** [comment]
Setting env vars should be sufficient. E.g., setting env var `DD_ENV:dev` should tag the logs collected by the extension with `env:dev`. No?

**Comment by olup** [comment]
Yes that works, but the forwarder (and the extension) is supposed to tag logs with all the tags I put on my AWS resources - according to the documentation. It's a very useful thing. Isn't it a bug that I can't?

**Comment by tianchu** [comment]
Enriching Lambda resource tags to logs require setting up the Datadog AWS integration. Did you set that up?

**Comment by olup** [comment]
You mean, activating that from DD admin panel ? The integration is activated - but maybe misconfigured ? Is there a specific thing to activate to have this work ?

**Comment by tianchu** [comment]
@olup do you mind moving this to a [datadog support](https://www.datadoghq.com/support/) ticket instead?

**Comment by tianchu** [comment]
Closing in favor of following up through the support channel for deeper investigation regarding specific account set up.
