### ISSUE TITLE
External/Auto instrumented services don't appear to be tagged as a separate service?

### ISSUE THREAD

**Issue by ZacharyThomas** [DataDog/datadog-lambda-extension#59]
Hi all,

We have a lambda which is using the datadog-python layer (3.54) and log forwarding (3.42).  We just added this layer (v21) to the lambda, but all of our RDS (postgres) spans immediately switched from being shown as a separate service to no longer being shown as a separate service.  Is there an obvious fix to this problem here?

**Comment by tianchu** [comment]
@ZacharyThomas, I saw your support ticket as well. Thanks for flagging this issue. Another change in our system caused this "side-effect", we are working on a fix.

**Comment by ZacharyThomas** [comment]
It looks like you all fixed this upstream somehow. We started getting our service traces split out again yesterday.

**Comment by tianchu** [comment]
@ZacharyThomas Yes, we did make a change in our backend :)
