### ISSUE TITLE
DD_EXTENSION | ERROR | Cannot decode v0.4 traces payload

### ISSUE THREAD

**Issue by uttrasey** [DataDog/datadog-lambda-extension#61]
We are using version 20 of the datadog lambda extension layer on the AL2 lambda runtime. We are sometimes seeing errors like the below on the Lambda:

```
arn:aws:lambda:eu-central-1:464622532012:layer:Datadog-Extension:21
```

2022-04-25 16:00:37 UTC | DD_EXTENSION | ERROR | Cannot decode v0.4 traces payload: read tcp 127.0.0.1:8126->127.0.0.1:49232: i/o timeout

We are upgrading to version 21 to see if it either solves the problem or provides more diagnostics.

Any advice would be great

**Comment by uttrasey** [comment]
Still occurs with v21

**Comment by maxday** [comment]
@uttrasey This should be fixed with v22.
Let us know how it goes after upgrading, thanks!

**Comment by roger-obando** [comment]
> @uttrasey This should be fixed with v22. Let us know how it goes after upgrading, thanks!

For those of us using the Serverless Datadog Plugin how do we upgrade to v22?

**Comment by uttrasey** [comment]
> @uttrasey This should be fixed with v22. Let us know how it goes after upgrading, thanks!

Looks like it did the trick. Thanks, @maxday 👏
