### ISSUE TITLE
Implement AWS integration "Host Tags"

### ISSUE THREAD

**Issue by fatbasstard** [DataDog/datadog-lambda-extension#8]
The AWS integration has the "host tags", tags that are applies to all hosts and metrics (See also: https://docs.datadoghq.com/integrations/amazon_web_services/ (`Optionally, add tags to all hosts and metrics.`)

These tags are not added to Lambda's using the Extension, can these be added?

**Comment by tianchu** [comment]
@fatbasstard Sorry for the late reply, we forgot to set up this new repo with our JIRA for tracking 🙇‍♂️ . I can see why this is useful and I just logged it as a ticket for our team to triage.

**Comment by fatbasstard** [comment]
Hi @tianchu,

Any news on the status of this ticket?

**Comment by DarcyRaynerDD** [comment]
Hi @fatbasstard, this feature should be generally available now for lambda's using the Extension. Are you able to see the tags coming through now?

**Comment by fatbasstard** [comment]
Hi @DarcyRaynerDD ,

Just validated and indeed, the tags are in there now! Thanks for the headsup 👍
