### ISSUE TITLE
fyi minor type in v28 release notes

### ISSUE THREAD

**Issue by mstumpfx** [DataDog/datadog-lambda-extension#84]
https://github.com/DataDog/datadog-lambda-extension/releases/tag/v28
Either
`Adds inferred spans for SNS` should be `Adds inferred spans for S3`
or the link to the PR from SNS is incorrectly pointing at s3 (which is also in the release notes for v29)

**Comment by tianchu** [comment]
@jcstorms1 can you help update the release notes?

**Comment by jcstorms1** [comment]
Thanks for the heads up @mstumpfx. I've updated the v28 release with the correct PR for SNS.
