### ISSUE TITLE
Missing logs and APM traces when a lambda timeout happens

### ISSUE THREAD

**Issue by pvicente** [DataDog/datadog-lambda-extension#89]
During some tests I had timeout in lambda, was running more than 15 minutes and the final logs were missed in datadogs and traces around the whole execution.

I reduced the timeout to 850 seconds and enabled the `DD_TRACE_DEBUG = true` but I couldn't see anything in logs.

See screenshots of latest logs of lambda execution in datadog and cloudwatch (Highlighted the ones missing in cloudwatch END, REPORT and task timeout):

![Screenshot 2022-10-27 at 10 35 16](https://user-images.githubusercontent.com/471109/198234203-7c37f56d-d991-4c09-b117-5de73fba1c97.png)

<img width="1797" alt="Screenshot 2022-10-27 at 10 18 09" src="https://user-images.githubusercontent.com/471109/198233859-5e78d2cb-f377-4519-b2d9-7759ed3515b6.png">

## Libraries in use:

```
datadog-lambda 4.63.0 The Datadog AWS Lambda Library
├── datadog >=0.41,<0.42
│   ├── decorator >=3.3.2 
│   └── requests >=2.6.0 
│       ├── certifi >=2017.4.17 
│       ├── charset-normalizer >=2,<3 
│       ├── idna >=2.5,<4 
│       └── urllib3 >=1.21.1,<1.27 
├── ddtrace >=1.4.1,<2.0.0
│   ├── attrs >=19.2.0 
│   ├── bytecode * 
│   ├── cattrs * 
│   │   ├── attrs >=20 (circular dependency aborted here)
│   │   └── exceptiongroup * 
│   ├── ddsketch >=2.0.1 
│   │   ├── protobuf >=3.0.0 
│   │   └── six * 
│   ├── envier * 
│   ├── jsonschema * 
│   │   ├── attrs >=17.4.0 (circular dependency aborted here)
│   │   └── pyrsistent >=0.14.0,<0.17.0 || >0.17.0,<0.17.1 || >0.17.1,<0.17.2 || >0.17.2 
│   ├── packaging >=17.1 
│   │   └── pyparsing >=2.0.2,<3.0.5 || >3.0.5 
│   ├── protobuf >=3 (circular dependency aborted here)
│   ├── six >=1.12.0 (circular dependency aborted here)
│   ├── tenacity >=5 
│   ├── typing-extensions * 
│   └── xmltodict >=0.12 
└── wrapt >=1.11.2,<2.0.0
```

**Comment by astuyve** [comment]
Hi - unfortunately this is a tricky situation as the Datadog Lambda Extension is killed alongside a Lambda Function when a function times out.

For nodejs, this issue is fixed today with layer 86 and [this feature](https://github.com/DataDog/dd-trace-js/pull/2476).

We're working on the same for Python, and will update this issue when completed.

Thanks!

**Comment by astuyve** [comment]
[this PR](https://github.com/DataDog/dd-trace-py/pull/4853) will support sending APM spans before a timeout for Python.

**Comment by pvicente** [comment]
> [this PR](https://github.com/DataDog/dd-trace-py/pull/4853) will support sending APM spans before a timeout for Python.

So it's just a matter to update `dd-trace-py` to version 1.9.0 when it's released? nothing else? What about the missing logs?

**Comment by tianchu** [comment]
cc: @DylanLovesCoffee for the missing logs.

**Comment by talberkoMelio** [comment]
Any update on this?

**Comment by pvicente** [comment]
With version 44 I've got in APM traces the error "Impending Timeout: Datadog detected an Impending Timeout" when this is happening so I can monitor it with timeout metric and add a link to the search of this error in APM. See 

<img width="535" alt="Screenshot 2023-07-18 at 11 07 19" src="https://github.com/DataDog/datadog-lambda-extension/assets/471109/8e9d023f-f739-4e39-930e-d715c7a8b6c3">

<img width="1597" alt="Screenshot 2023-07-18 at 11 08 04" src="https://github.com/DataDog/datadog-lambda-extension/assets/471109/a97c26e1-506e-4065-a427-245ce4fb8b80">

**Comment by DylanLovesCoffee** [comment]
Closing in favor of `Impending Timeout`s on all runtimes https://github.com/DataDog/datadog-agent/pull/21481
