### ISSUE TITLE
VPC Bound AWS Lambda

### ISSUE THREAD

**Issue by sharmam-caremonitor** [DataDog/datadog-lambda-extension#90]
Hi team

I am getting timeout while using Datadog Layer Extension. Any workaround to do away with timeout?

**Comment by astuyve** [comment]
Hi,

Thanks for reaching out - if you have already followed the [documentation](https://docs.datadoghq.com/serverless/configuration/?tab=datadogcli#send-telemetry-over-privatelink-or-proxy) for privatelink and are still experiencing issues, please open a support ticket directly so we can help more.

Thanks!
