### ISSUE TITLE
Is logs being not flushed until the end of lambda function spun down still an issue? 

### ISSUE THREAD

**Issue by inyutin** [DataDog/datadog-lambda-extension#98]
Hello!

More than a year ago there was an issue: https://github.com/DataDog/datadog-lambda-extension/issues/29

Let me quote the main problem that the user had:

> I my testing I have seen that logs take ~10 minutes to appear in datadog log explorer from my lambda function. The reason seems to be that the logs are not flushed until the function is spun down by AWS.

A person from developer side of datadog-lambda-extension answered: 
> We are in touch with AWS about possible improvements to resolve this issue.

My question is it still a problem after one year passed? Are there any workarounds  ?

**Comment by astuyve** [comment]
Hi @inyutin - thanks for reaching out! I believe this is a misunderstanding, so let me help clarify how the Datadog Extension chooses a flush strategy.

When a function begins receiving invocations, we immediately flush data at the *end* of the invocation (after the response has returned to the Lambda function caller). After several invocations (3, I believe), the extension will buffer data and flush *periodically*.

This appears to cover the use cases quite nicely. For low traffic functions like cron jobs, development iteration cycles, or other infrequently invoked functions - data is sent immediately. It also covers the high load, production level workloads with hundreds or thousands of serial invocations over time. In this case the periodic flushing occurs so frequently that data also arrives in near real time with limited overhead.

This flushing strategy is configurable, and you can force Datadog to flush data after every transaction by setting the environment variable`DD_SERVERLESS_FLUSH_STRATEGY` to `end`.

Please feel free to leave a comment and reopen this issue if you're experiencing something specific. Thanks!

**Comment by Dreamescaper** [comment]
@astuyve 
I have this issue as well. It's not about flush strategy, it's about this case:

> Hi @stalar, the function will send data at the end of the first invocation. The issue is that we might not actually have all of the data yet because the logs API is asynchronous. So, there is a possibility that some data will not arrive until a subsequent invocation (or spindown of the environment after ~10 minutes).

So it doesn't help to change DD_SERVERLESS_FLUSH_STRATEGY.  

We still need a workaround for this case. Is it possible to make the logs API synchronous somehow? Of force waiting at the end of the execution until the logs are processed, so that all of them are sent at the end of the invocation?
